server:
  port: 8080
logging:
  level:
    root: INFO        # 전체 애플리케이션의 기본 로그 레벨 설정
spring:
  datasource:
    driver-class-name: org.postgresql.Driver # PostgreSQL JDBC ????? ?????.
    url: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}?serverTimezone=UTC
    platform: postgres # ???? ?????? ???? ?????.
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time-zone: UTC
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
kakao:
  host-name: KAKAO
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  logout-redirect-uri: ${KAKAO_LOGOUT_REDIRECT_URI}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-time: 900000 #60*15*1000
  refresh-token-expiration-time: 259200000 #60*60*24*3*1000

scheduled:
  fixedDelay:
    crawling: "${FIXED_DELAY_EXPRESSION_CRAWLING}"