# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crawler-core.fullname" . }}
  labels:
    app: {{ include "crawler-core.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "crawler-core.name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
